### ISSUE TITLE
BUG: very slow web interface by large number of query jobs

### ISSUE THREAD

**Issue by kimakan** [django-daiquiri/daiquiri#178]
A very large number of not archived query jobs leads to a de facto freeze of the query app. It's especially an issue for the anonymous user.
The solution could be a limit on the number of query jobs. After reaching the limit (app settings), the oldest query jobs could be automatically archived. Another viable solution is to  implement a pagination feature. In this case, not all query jobs will be rendered at once which will improve the overall performance.

**Comment by jochenklar** [comment]
Hi @kimakan @agy-why ! (still reading this :) If the API for a list is slow, it can be that database queries are performed for every row. Then you have 10000 queries for 10000 rows! Django offers 2 functions to optimize db access `select_related` and `prefetch_related`. Also there is the `django-debug-toolbar` which can show all database queries for a request. @triole might now a bit about this since we use it heavily in RDMO.

**Comment by kimakan** [comment]
The database query seem not to be the culprit of the problem. The API request to `.../query/api/jobs/tables/` results in a single query that looks like this
```
Executed SQL
    SELECT "daiquiri_jobs_job"."id",
           "daiquiri_jobs_job"."owner_id",
           "daiquiri_jobs_job"."client_ip",
           ...
           "daiquiri_query_queryjob"."metadata",
           "daiquiri_query_queryjob"."uploads",
           "daiquiri_query_queryjob"."pid"
      FROM "daiquiri_query_queryjob"
     INNER JOIN "daiquiri_jobs_job"
        ON ("daiquiri_query_queryjob"."job_ptr_id" = "daiquiri_jobs_job"."id")
     WHERE ("daiquiri_jobs_job"."owner_id" = 1 AND "daiquiri_jobs_job"."phase" = 'COMPLETED')
     ORDER BY "daiquiri_jobs_job"."creation_time" DESC
     LIMIT 100
```
IMHO, the problem lies in the construction of the fetched metadata
https://github.com/django-daiquiri/daiquiri/blob/4eab550c9e00745b5538bdb236fe93f0c346f33b/daiquiri/query/utils.py#L103-L129

If the user tables contain many columns, the processing here takes a lot of time. 
```python
         if job.metadata: 
             table['columns'] = job.metadata.get('columns', {}) 
  
             for column in table['columns']: 
                 column['query_strings'] = [column['name']] 
```
That's why this problem was encountered in the GAIA archive first. Some of the tables there contain more than 150 columns, hence the amount of metadata in the user tables  adds up quiet fast. I tested this by commenting out the code above and the performance issues were gone completely. However, I'm not sure how to solve it yet.

**Comment by kimakan** [comment]
The simplest solution for now is to remove the user schema from the column search, see commit 8f9acf223f73e02f230ed70529d7fe9343bbe055.
I will leave some time for discussion before I make a PR for it.
