### ISSUE TITLE
Bug with access level filtering

### ISSUE THREAD

**Issue by jochenklar** [django-daiquiri/daiquiri#20]
Access level filtering does not work if both `access_level` or `metadata_access_level` and `groups` are set in `daiquiri.metadata.models.Database`.

**Comment by agy-why** [comment]
@kimakan Is that not the same bug as #114  ?

**Comment by kimakan** [comment]
It seems that it was fixed back then with https://github.com/django-daiquiri/daiquiri/commit/7794fcf115194285af1fa324a1755adfb65733dc
The bug #114 is not the same but closely related as it was caused by the implementation introduced here first. 
However, #114 does not mention access_level by groups and thus, it was not tested with group access. This might be still an issue. 
I would suggest to change the current code from 
https://github.com/django-daiquiri/daiquiri/blob/814cffa5365051798ec21408ef520b476339ed24/daiquiri/core/utils.py#L168-L176

to 
```python
        if 'access_level' not in item or item['access_level'] == ACCESS_LEVEL_PUBLIC:
            filtered_items.append(item)
        elif item['access_level'] == ACCESS_LEVEL_INTERNAL:
            if user is not None:
                if user.is_authenticated:
                    filtered_items.append(item)
        elif item['access_level'] == ACCESS_LEVEL_PRIVATE and 'groups' in item:
            if user is not None:
                if user.is_authenticated and user.groups.filter(name__in=item['groups']).exists():
                    filtered_items.append(item)
```
In this way, it will stay consistent with the implementation for `ACCESS_LEVEL_INTERNAL`.

**Comment by agy-why** [comment]
Sounds good! 

I am wondering if we could improve further:

What about case with `item['access_level'] == ACCESS_LEVEL_PRIVATE` but `groups` key not in item? This would be difficult to debug: having correct `ACCESS_LEVEL` and being logged-in is not sufficient. A badly build context (missing `groups` key in item) would lead to the return of an empty `filtered_items`. 

What do you think if we raise an error in that case: `RuntimeError`?

**Comment by kimakan** [comment]
The logged-in user has to be in a group to access private schemas/tables. An empty `filtered_items` is a valid response, in my opinion. If there are only private schemas, then the user should get an empty list of items, as expected. 
Regarding your example about the missing `groups` key in item, we already check for this
https://github.com/django-daiquiri/daiquiri/blob/814cffa5365051798ec21408ef520b476339ed24/daiquiri/core/utils.py#L174

**Comment by agy-why** [comment]
What about user's private schema? Is it treated as INTERNAL? I am wondering about the case of a user trying to access it own table, with `item` not having a `groups` key (the latter could be `[]`)?

this would work:
```python
item = {'access_level': ACCESS_LEVEL_PRIVATE, 'groups': []}
```
but this won't:
```python
item = {'access_level': ACCESS_LEVEL_PRIVATE}
```

But maybe the access to the private schema is treated differently? can you confirm?

**Comment by kimakan** [comment]
The private schema doesn't use the same metadata schema as the science db. 
The private schemas/tables (user specific) are always fetched by `.../query/api/jobs/tables/` and are not checked by the code we discuss here. 
https://github.com/django-daiquiri/daiquiri/blob/814cffa5365051798ec21408ef520b476339ed24/daiquiri/query/static/query/js/services/query.js#L138
https://github.com/django-daiquiri/daiquiri/blob/814cffa5365051798ec21408ef520b476339ed24/daiquiri/query/static/query/js/services/query.js#L13
The corresponding user is then checked here...
https://github.com/django-daiquiri/daiquiri/blob/814cffa5365051798ec21408ef520b476339ed24/daiquiri/query/utils.py#L103-L106
..and here.
https://github.com/django-daiquiri/daiquiri/blob/814cffa5365051798ec21408ef520b476339ed24/daiquiri/query/utils.py#L36-L42

**Comment by agy-why** [comment]
ok. Can you open a PR for this?
