### ISSUE TITLE
Why mysql ? 

### ISSUE THREAD

**Issue by obartunov** [django-daiquiri/daiquiri#46]
How it is difficult to port daiquiri to postgres ?

**Comment by jochenklar** [comment]
Hi, Daiquiri already works fine with PostgreSQl. Actually using PostgreSQL and [pgsphere](https://pgsphere.github.io/) enables fast querieing on large observational datasets, like on gaia.aip.de. We are currently working on a (better) documantation. The first draft is already online at https://django-daiquiri.github.io/docs/.
