### ISSUE TITLE
add ACCOUNT_ADAPTER and ACCOUNT_SIGNUP_FORM to variables set via env

### ISSUE THREAD

**Issue by roerch** [django-daiquiri/daiquiri#47]
Since 4MOST uses a more complex user management, we need to use a dedicated adapter and signup form. These variables currently need to be set in the daiquiri settings directory. Adding them to the variables set via .env would remove this modification of daiquiri files.

Pull request will follow.

**Comment by jochenklar** [comment]
Hi, these kind of project specific modifications can be done in the base.py file of the daiquiri-app. This file overrides the default values much like then enviroment variables with the benefit that they are part of the versioned source code. I would recommend to only put settings which are machine specific like pathes and passwords in the enviroment.

**Comment by roerch** [comment]
That worked... consider this issue closed.
