### ISSUE TITLE
IDEA: Highlighting of code in the Documentation (WP)

### ISSUE THREAD

**Issue by agy-why** [django-daiquiri/daiquiri#51]
# CONTEXT

Highlighting is helpful and allows better reading

# PROBLEM

There is no highlighting possibility in the Documentation (ex: https://gaia.aip.de/cms/documentation/tap-interface/) 

# REQUEST

Maybe there is plugin for WP (that is easy to maintain) ? Maybe some flag in the HTML source code?

**Comment by agy-why** [comment]
I found three plugins that could be considered, I'll test compatibility soon.
A list of code highlighter for WP to test:
* https://de.wordpress.org/plugins/ank-prism-for-wp/
* https://de.wordpress.org/plugins/syntaxhighlighter/
* https://de.wordpress.org/plugins/crayon-syntax-highlighter/

**Comment by kimakan** [comment]
The feature was added in the pull-request [#89](https://github.com/django-daiquiri/daiquiri/pull/89)
