### ISSUE TITLE
FEATURE: Allow only certain characters in the "table name" form in the query interface 

### ISSUE THREAD

**Issue by galkinAIP** [django-daiquiri/daiquiri#78]
The "table name" currently allows spaces, etc. in the Query form. The form should allow only alphanumerical characters and "_", "-".

**Comment by triole** [comment]
Fixed here: https://github.com/django-daiquiri/daiquiri/commit/325fde63921f4180d6fe84a709888b66123b3b31

**Comment by jochenklar** [comment]
Hi @galkinAIP , @triole , any reason why this was not merged before? I would add a setting for this though. Another possibility was to chain a `django.core.validators.RegexValidator` with `r'^[\w]+\Z'` with the current `TableNameValidator` (and get rid of the `-` as well).

Anyway, is it just to make cli access for admins better? Daiquiri seems to work fine with weird tablenames.

**Comment by glaubervila** [comment]
> Hi @galkinAIP , @triole , any reason why this was not merged before? I would add a setting for this though. Another possibility was to chain a `django.core.validators.RegexValidator` with `r'^[\w]+\Z'` with the current `TableNameValidator` (and get rid of the `-` as well).
> 
> Anyway, is it just to make cli access for admins better? Daiquiri seems to work fine with weird tablenames.

Hi, I am testing daiquiri and in my environment, when there is space in the table name the download fails.

**Comment by kimakan** [comment]
Can confirm. Currently, whitespaces in the `table name` break the download.
