### ISSUE TITLE
User name to schema names

### ISSUE THREAD

**Issue by harenk** [django-daiquiri/daiquiri#79]
The mapping of Username (for registered users) to a schema name creates cewrtain pitfalls:
although proprerly escaped, special chars create difficulties when formulating queries:
e.g.: 
my.name as username -> datacoll_user_my.name needs always the (arcane) quotations rules applied, and e.g. using an upload feature for  VO table fails for subsequent use. 
Suggestion 1:
do not allow special chars in usernames, especially '.' and  '@'
Suggestion 2: 
replace all remaining special characters by '_'

**Comment by jochenklar** [comment]
I added a new validator which we can use in the future by adding:

```python
ACCOUNT_USERNAME_VALIDATORS = 'daiquiri.auth.validators.username_validators'
```

to `settings/base.py`.
